[theme]
base = "light"
primaryColor = "#1D4ED8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FF"
textColor = "#0B132B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
