ERROR_CATALOG = {
    "INVALID_DATE_RANGE": {
        "status_code": 400,
        "error_code": "INVALID_DATE_RANGE",
        "message": "La fecha inicial debe ser menor que la fecha final.",
        "hint": "Asegure que start sea anterior a end.",
        "where": "market_utils.validate_not_future",
    },
    "FUTURE_DATE": {
        "status_code": 400,
        "error_code": "FUTURE_DATE",
        "message": "No se permiten fechas futuras.",
        "hint": "Use una fecha final menor o igual a hoy.",
        "where": "market_utils.validate_not_future",
    },
    "INVALID_API_KEY": {
        "status_code": 401,
        "error_code": "INVALID_API_KEY",
        "message": "API key invalida o ausente.",
        "hint": "Verifique el header x-api-key.",
        "where": "security.require_internal_api_key",
    },
    "TICKER_NOT_FOUND": {
        "status_code": 404,
        "error_code": "TICKER_NOT_FOUND",
        "message": "No se encontraron datos para el ticker solicitado.",
        "hint": "Revise el ticker o el rango de fechas.",
        "where": "market_client.get_prices",
    },
    "INSUFFICIENT_OBS_VAR": {
        "status_code": 400,
        "error_code": "INSUFFICIENT_OBS_VAR",
        "message": "No hay suficientes observaciones para calcular VaR.",
        "hint": "Amplie el horizonte de fechas o use activos con mas historial.",
        "where": "risk_service.calculate_var",
    },
    "INSUFFICIENT_OBS_CAPM": {
        "status_code": 400,
        "error_code": "INSUFFICIENT_OBS_CAPM",
        "message": "No hay suficientes observaciones para calcular CAPM.",
        "hint": "Amplie el horizonte de fechas o revise la disponibilidad del benchmark.",
        "where": "capm_service",
    },
    "INSUFFICIENT_OBS_PORTFOLIO": {
        "status_code": 400,
        "error_code": "INSUFFICIENT_OBS_PORTFOLIO",
        "message": "No hay suficientes observaciones para optimizacion de portafolio.",
        "hint": "Use un rango de fechas mas amplio.",
        "where": "portfolio_service.build_efficient_frontier",
    },
    "EXTERNAL_API_FAILURE": {
        "status_code": 503,
        "error_code": "EXTERNAL_API_FAILURE",
        "message": "La API externa no respondio correctamente.",
        "hint": "Intente nuevamente mas tarde.",
        "where": "external_provider",
    },
    "INVALID_PORTFOLIO_WEIGHTS": {
        "status_code": 400,
        "error_code": "INVALID_PORTFOLIO_WEIGHTS",
        "message": "Los pesos del portafolio son invalidos.",
        "hint": "Los pesos deben ser no negativos y sumar 1.0 o 100%.",
        "where": "schemas",
    },
    "INVALID_CONFIDENCE_LEVEL": {
        "status_code": 400,
        "error_code": "INVALID_CONFIDENCE_LEVEL",
        "message": "El nivel de confianza enviado no es valido.",
        "hint": "Use valores entre 0.10 y 0.99.",
        "where": "schemas",
    },
}